site:
  title: Neo4j Developer Portal
  url: /developer

content:
  sources:
  - url: https://github.com/neo4j-documentation/developer-guides.git
    branches: master
    exclude:
    - '!**/_includes/*'
    - '!**/readme.adoc'
    - '!**/README.adoc'
  - url: https://github.com/neo4j-documentation/labs-pages.git
    branches: master
ui:
  bundle:
    url: ui/build/ui-bundle.zip
    snapshot: true
urls:
  html_extension_style: indexify
asciidoc:
  extensions:
  - ./extensions/remote-include/remote-include-processor
  - ./extensions/macros/macros
  attributes:
    experimental: ''
    page-disabletracking: true
