site:
  title: Neo4j Developer

content:
  sources:
  - url: https://github.com/neo4j-contrib/neo4j-spark-connector
    branches: ['4.0']
    start_path: 'doc/docs'

output:
  dir: ./build/site/developer
ui:
  bundle:
    url: ui/build/ui-bundle.zip
    snapshot: true
urls:
  html_extension_style: indexify
asciidoc:
  extensions:
  - ./extensions/remote-include/remote-include-processor
  - ./extensions/macros/macros
  attributes:
    experimental: ''
    page-component: kb
    page-theme: kb
    page-canonical-root: /developer/spark
    # page-breadcrumbs:
    #   - name: Neo4j KB
    #     url: https://neo4j.com/developer/kb/
